### PR TITLE
fix: handle several reachable panics

### LINKED ISSUE #2174: Reachable panic in `opaque_def_to_vir`
## PoC
```rust
use vstd::prelude::*;
verus! {
pub fn f() -> impl Copy { 1u8 }
fn main() {}
}
```

## Panic Log
```
warning: verus was compiled in debug mode, which will result in worse performance

thread 'rustc' (1362312) panicked at rust_verify/src/rust_to_vir_base.rs:2280:26:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: <core::option::Option<alloc::sync::Arc<vir::ast::GenericBoundX>>>::unwrap
             at /home/root/.rustup/toolchains/1.93.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1016:21
   5: rust_verify::rust_to_vir_base::opaque_def_to_vir
             at ./source/rust_verify/src/rust_to_vir_base.rs:2280:26
   6: rust_verify::rust_to_vir_base::check_fn_opaque_ty
             at ./source/rust_verify/src/rust_to_vir_base.rs:2217:5
   7: rust_verify::rust_to_vir::check_item
             at ./source/rust_verify/src/rust_to_vir.rs:184:21
   8: rust_verify::rust_to_vir::crate_to_vir
             at ./source/rust_verify/src/rust_to_vir.rs:482:25
   9: <rust_verify::verifier::Verifier>::construct_vir_crate::<rust_verify::verifier::Reporter>
             at ./source/rust_verify/src/verifier.rs:2695:13
  10: <rust_verify::verifier::VerifierCallbacksEraseMacro as rustc_driver_impl::Callbacks>::after_expansion
             at ./source/rust_verify/src/verifier.rs:3093:64
  11: <rustc_interface::passes::create_and_enter_global_ctxt<core::option::Option<rustc_interface::queries::Linker>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2}>::{closure#2} as core::ops::function::FnOnce<(&rustc_session::session::Session, rustc_middle::ty::context::CurrentGcx, alloc::sync::Arc<rustc_data_structures::jobserver::Proxy>, &std::sync::once_lock::OnceLock<rustc_middle::ty::context::GlobalCtxt>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_middle::arena::Arena>, &rustc_data_structures::sync::worker_local::WorkerLocal<rustc_hir::Arena>, rustc_driver_impl::run_compiler::{closure#0}::{closure#2})>>::call_once::{shim:vtable#0}
  12: rustc_interface::interface::run_compiler::<(), rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Env
Verus Version: 2026.02.11 c780c07

## Playground Link
https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=42c8c13a5c3e3db5659b07caaf07c5c6

### PR DESCRIPTION
**Pull request by Marsman1996**
This PR handles #2175, #2184 and more
Fix #2174

My pipeline depends on Verus returning errors in JSON format. 
When Verus panics, no JSON message is produced, which breaks the pipeline. 
This PR changes the behavior to return a structured error message instead of panicking.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/verus-lang/verus/blob/main/LICENSE).</small>

### CODE REVIEW

**Comment by Marsman1996** [comment]
## `check_expr_handle_mut_arg`
https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=82beda3c9809ccf0d59539c8b381193b
### PoC
```rust
use vstd::prelude::*;
verus!{
proof fn p(){
    let _f = |x:int| -> int { return x; };
}
fn main(){}
}
```
### Log
```
thread 'rustc' (42) panicked at vir/src/modes.rs:2891:30:
internal error: missing return type
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## `binopkind_to_binaryop_inner`
https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=faaee97e93ac1ef62099c7780d2124ec

### PoC
```rust
use vstd::prelude::*;
verus! {
fn f() {
    let x = true & false;
    let z = true ^ false;
    let y = true | false;
}
fn main(){}
}

```

### Log
```
thread 'rustc' (42) panicked at rust_verify/src/rust_to_vir_expr.rs:3046:21:
bitwise AND for bools (i.e., the not-short-circuited version) not supported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: source/vir/src/sst_to_air_func.rs [hunk 1]
```diff
@@ -698,7 +698,12 @@ pub fn func_decl_to_air(ctx: &mut Ctx, function: &FunctionSst) -> Result<Command
             }
         }
     } else {
-        assert!(!function.x.has.has_ensures); // no ensures allowed on spec functions yet
+        if function.x.has.has_ensures {
+            return Err(crate::messages::error(
+                &function.x.ret.span,
+                "no ensures allowed on spec functions yet",
```
Comment (tjhance) [inline source/vir/src/sst_to_air_func.rs]: don't say "yet", just say "ensures clause unsupported on spec function"

File: source/vir/src/modes.rs [hunk 2]
```diff
@@ -2888,7 +2888,7 @@ fn check_expr_handle_mut_arg(
             match (e1, typing.ret_mode) {
                 (None, _) => {}
                 (Some(v), None) if is_unit(&v.typ) => {}
-                (_, None) => panic!("internal error: missing return type"),
+                (_, None) => return Err(error(&expr.span, "missing return type")),
```
Comment (tjhance) [inline source/vir/src/modes.rs]: please add 'Verus Internal Error' to the error message

**Review by tjhance — CHANGES_REQUESTED** [review]
the bitwise operator change looks fine; the other 2 are internal errors (the expected invariants on verus's internal state are being violated) so they need further investigation. I'd appreciate it if (in addition to this PR) you could:

 * leave https://github.com/verus-lang/verus/issues/2175 open
 * file an additional issue with the closure "missing return type" example

thanks!

**Comment by Marsman1996** [comment]
> * file an additional issue with the closure "missing return type" example

See #2184

**Comment by Marsman1996** [comment]
The new commit fixes #2174
```
error: The verifier does not yet support the following Rust feature: this type of bound
 --> ./test/impl.rs:3:15
  |
3 | pub fn f() -> impl Copy { 1u8 }
  |               ^^^^^^^^^

error: aborting due to 1 previous error
```

just like 
https://github.com/verus-lang/verus/blob/ac50b8fd7fa6822736f9ef42bff8ecaba8aefc29/source/rust_verify/src/rust_to_vir_base.rs#L2328
and
https://github.com/verus-lang/verus/blob/ac50b8fd7fa6822736f9ef42bff8ecaba8aefc29/source/rust_verify/src/rust_to_vir_base.rs#L1791

**Comment by tjhance** [comment]
thanks!
