### PR TITLE
verus_verify attribute: Properly desugar forloop

### LINKED ISSUE #2270: Compiler crashes with `for` loop inside `#[verus_verify]` function
If you have a function that adds verification via attributes rather than `verus!`, then a `for` loop without a `verus_spec` annotation will cause the compiler to crash when running verification. For instance, consider the following code (note the absence of `verus!`):

```
use vstd::prelude::*;

#[verus_verify]
fn for_loop_crashes_compiler()
{
    for i in 0..10 {
    }
}
```

Verifying this will cause an error message like:
```
thread 'rustc' (37588) panicked at /rustc-dev/4a4ef493e3a1488c6e321570238084b38948f6db/compiler\rustc_middle\src\ty\generic_args.rs:54:14:
index out of bounds: the len is 0 but the index is 0
```

It would be nice if this generated a nicer error message, since Verus novices who are trying to add verification to their code piecemeal may run into it and not understand what's going on. Though, if they ask Claude Opus it may tell them; that's how I figured out the root cause of this! Claude says:

> This is a Verus compiler bug — the for loop desugars into IntoIterator::into_iter() + Iterator::next() on [Range<usize>](vscode-file://vscode-app/c:/Programs/Microsoft%20VS%20Code/07ff9d6178/resources/app/out/vs/code/electron-browser/workbench/workbench.html), and Verus's modified rustc crashes when resolving the generic arguments for those trait impls (the 0-length generic args being indexed at 0).

### PR DESCRIPTION
**Pull request by ziqiaozhou**
It fixes #2270 

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/verus-lang/verus/blob/main/LICENSE).</small>

### CODE REVIEW

File: source/builtin_macros/src/attr_rewrite.rs [hunk 1]
```diff
@@ -282,6 +282,25 @@ impl VisitMut for ExecReplacer {
...
+
+    fn visit_expr_for_loop_mut(&mut self, for_loop: &mut syn::ExprForLoop) {
+        syn::visit_mut::visit_expr_for_loop_mut(self, for_loop);
+
+        if !self.erase.keep() {
+            return;
+        }
+
+        // In verification mode, even without verus spec on the loop, we still
+        // need to desugar the forloop.
```
Comment (jaylorch) [inline source/builtin_macros/src/attr_rewrite.rs]: I suggest a space between `for` and `loop`.

File: source/builtin_macros/src/attr_rewrite.rs [hunk 2]
```diff
@@ -282,6 +282,25 @@ impl VisitMut for ExecReplacer {
...
+        // Thus, add empty verus_spec if not exists
```
Comment (jaylorch) [inline source/builtin_macros/src/attr_rewrite.rs]: For greater clarity, I suggest rewording this line to:
```
// So, if there's no `verus_spec` attribute, we need to add an empty one.
```
