### PR TITLE
Fix `#[verus_spec]` for methods in `Impl` blocks

### LINKED ISSUE #1916: `#[verus_spec]` macro errors within `impl` blocks.
# Description

The following code does not compile

```rust

pub struct Foo;

impl Foo {
    #[verus_spec(ret =>
        with
            Tracked(c): Tracked<&mut DekoPointsTo<()>>
        requires
            true,
        ensures
            ret == 1,
    )]
    fn test(a: u64, b: u64) -> u64 {
        1
    }
}
```

Moving the function body outside `Foo` makes Rust compiler happy, however. This should have something to do with the proc_macro bug. Also a sidenote, adding a trailing comma after arguments in `with` block causes macro expansion error.

### PR DESCRIPTION
**Pull request by rikosellic**
Another attempt to fix #1916. In #1932, we found it impossible for `verus_spec` to determine whether a function is inside an Impl block (it is always set to `false` now, i.e., not in a block).  My solution is to apply `[verus_verify]` at the `Impl` block level, which will insert an internal `verus_impl_method_marker` into each method, and `verus_spec` can use to identify whether the function belongs to an `Impl` block.

However, providing a clear error message when verification fails is tricky. Some functions may still verify successfully even without `[verus_verify]` at the block level, for example, if `dual_spec` applies or if the specification does not include an `ensures` clause.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/verus-lang/verus/blob/main/LICENSE).</small>

### CODE REVIEW

**Comment by rikosellic** [comment]
#1932 now provides a different approach to fix the same issue. You may choose whichever you prefer.

**Comment by hiroki-chen** [comment]
BTW, any interest in fixing #1936 along with this PR?

File: source/builtin_macros/src/attr_rewrite.rs [hunk 1]
```diff
@@ -364,6 +375,35 @@ pub(crate) fn rewrite_verus_spec_on_fun_or_loop(
...
+                if let Some(ident) = attr.path().get_ident() {
+                    if ident == "allow" {
+                        if let syn::Meta::List(meta_list) = &attr.meta {
+                            return !meta_list
+                                .tokens
+                                .to_string()
+                                .contains("verus_impl_method_marker");
+                        }
+                    }
+                }
```
Comment (ziqiaozhou) [inline source/builtin_macros/src/attr_rewrite.rs]: Could you simplify the code?

For example,


```
let is_hidden_impl_marker = |attr: &syn::Attribute| {
    attr.path().get_ident().map_or(false, |ident| {
        ident == "allow" && matches!(&attr.meta, syn::Meta::List(meta_list)
            if meta_list.tokens.to_string().contains("verus_impl_method_marker"))
    })
};

// Check if the function has the impl method marker
let is_impl_fn = fun.attrs.iter().any(&is_hidden_impl_marker);

// Remove the marker attribute (internal use only)
fun.attrs.retain(|attr| !is_hidden_impl_marker(attr));
```

File: source/builtin_macros/src/attr_rewrite.rs [hunk 2]
```diff
@@ -151,6 +151,17 @@ pub(crate) fn rewrite_verus_attribute(
...
+    // Special handling for impl blocks, add marker attribute to each method for `#[verus_spec]`.
+    if let syn::Item::Impl(ref mut impl_block) = item {
+        for impl_item in &mut impl_block.items {
+            if let syn::ImplItem::Fn(ref mut method) = impl_item {
+                method.attrs.push(syn::parse_quote! {
+                    #[allow(unused, verus_impl_method_marker)]
+                });
+            }
+        }
+    }
```
Comment (ziqiaozhou) [inline source/builtin_macros/src/attr_rewrite.rs:169]: What if we have
```
#[verus_verify]
impl X {
   fn unverified() {}
}
```

verus_impl_method_marker should be applied only when the function has a verus_spec attribute.

**Review by ziqiaozhou — CHANGES_REQUESTED** [review]
Thanks for fixing the bug. 

Please add a test 
```
#[verus_verify]
impl X {
   fn unverified() {}
}
```

File: source/builtin_macros/src/attr_rewrite.rs (hunk 1 above)
Comment (rikosellic) [reply source/builtin_macros/src/attr_rewrite.rs]: Thanks!

File: source/builtin_macros/src/attr_rewrite.rs (hunk 2 above)
Comment (rikosellic) [reply source/builtin_macros/src/attr_rewrite.rs:169]: That's a good point, I've fixed it in the latest commit.

**Comment by hiroki-chen** [comment]
I don't know what exactly is causing the trouble but I just found that upgrading to the latest `verus_builtin_macro` (working commit is `bf6ffb4a`) panics my execution code.
